version: '3'

services:

  quicknode:
    container_name: quicknode
    image: openjdk
    restart: unless-stopped
    volumes:      
      - /data/ergo/.ergo:/ergo/.ergo
      - ./ergo.conf:/app/ergo.conf
      - ./ergo-4.0.42.jar:/app/ergo.jar
    ports:
      - 9053:9053
      - 9030:9030
    networks:
      - ergopad-net
    working_dir: /app
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 90s
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    command: java -jar -Xmx4G -Dlogback.stdout.level=WARN -Dlogback.file.level=WARN ergo.jar --mainnet -c ergo.conf

# this may require cmd: docker network create ergopad-net
networks:
  ergopad-net:
    external: true
